# Generated by Django 4.0.5 on 2024-01-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuopone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('Free_shipping', models.BooleanField()),
                ('discount_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Percentage', 'Percentage')], max_length=50)),
                ('amount', models.FloatField()),
                ('spent_limit', models.IntegerField()),
                ('category', models.ManyToManyField(to='category.category')),
            ],
        ),
    ]
