# Generated by Django 4.0.5 on 2024-01-19 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('vendor', models.CharField(blank=True, max_length=15, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', unique=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('order_status', models.CharField(blank=True, choices=[('Hold', 'Hold'), ('Shipment', 'Shipment'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash on Delivery', 'Cash on Delivery'), ('Bkash', 'Bkash'), ('Rocket', 'Rocket'), ('Nagad', 'Nagad')], max_length=50, null=True)),
                ('payment_number', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Canceled', 'Canceled')], max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('ordered_product', models.ManyToManyField(to='orders.orderedproduct')),
                ('used_cuopone', models.ManyToManyField(blank=True, null=True, to='coupon.cuopone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
